Resources:
  MyprimeraInstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0030e4319cbf4dbf2"
      KeyName:
      InstanceType: "t2.micro"
      BlockDeviceMappings:
        - DeviceName: "/dev/sdm"
          Ebs:
            VolumeType: "gp3"
            DeleteOnTermination: "true"
            VolumeSize: "10"
      SecurityGroups:
        - !Ref InstanceSecurityGroup
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      #VpcId: !Ref myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
